language: csharp
dist: trusty
sudo: true

os:
  - linux
  - osx

mono:
  - latest
  - 5.18.1
  - 5.16.0
  - 5.14.0
  - 5.12.0

#  - nightly

install:

script: ./mono/build-mono.sh && ./mono/test-mono.sh

allow_failures:
  - mono: nightly
